PushURL = "https://acc.sensorbucket.nl/api/uplinks/123123"
Authorization = "Bearer 123123"
Interval = "15s"
ReadoutPath = ""
SwitchPath = ""
CSVFolder = "./data"
Profile = [
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6],
    [4,5,6,7],
    [5,6,7,8],
    [6,7,8,9],
]
